version: "3"
services:
  products-service:
    image: nginx:alpine
    container_name: products-service
    restart: always
    volumes:
      - ./:/app:delegated
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:delegated
    ports:
      - "8080:80"
    expose:
      - "80"
    depends_on:
      - php
      - mongodb
  php:
    build: .
    container_name: products-service_php
    restart: always
    volumes:
      - ./:/app:delegated
      - ./docker/fpm.conf:/usr/local/etc/php-fpm.d/www.conf:delegated
  mongodb:
    image: mongo:latest
    container_name: products-service_mongo
    restart: always
    volumes:
      - ./data/db/mongo:/data/db
    ports:
      - "27020:27017"
    command: --storageEngine wiredTiger
