version: "3"
services:
  products-service:
    build: .
    volumes:
      - ./:/app:delegated
      - ./docker/fpm.conf:/usr/local/etc/php-fpm.d/www.conf:delegated
    environment:
      LOG_LEVEL: "debug"
      DEBUG: "true"

  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:delegated
      - ./:/app:delegated
    ports:
      - "8080:80"
    expose:
      - "80"
    depends_on:
      - products-service
