services:
  _defaults:
    public: true
    autowire: true

  action.greet:
    class: App\ProductsService\Actions\GreetAction
    arguments:
      $greeting: "Welcome to Products Service!"

  action.show_product:
    class: App\ProductsService\Actions\ShowProductAction

  action.list_product:
    class: App\ProductsService\Actions\ListProductAction

  action.find_product:
    class: App\ProductsService\Actions\FindProductAction
