imports:
  - { resource: framework.yml }
  - { resource: actions.yml }

services:
  _defaults:
    autowire: true

  MongoDB\Driver\Manager:
    class: MongoDB\Driver\Manager
    arguments:
      $uri: '%env(mongodb_server)%'

  Psr\Log\LoggerInterface:
    class: Symfony\Component\HttpKernel\Log\Logger
    arguments:
      $minLevel: '%env(LOG_LEVEL)%'
      $output: "php://stdout"

  App\ProductsService\Service\ProductServiceInterface:
    class: App\ProductsService\Service\ProductService

  App\ProductsService\Repository\ProductRepositoryInterface:
    class: App\ProductsService\Repository\ProductRepository
    arguments:
      - "@productRepositoryAdapter"

  productRepositoryAdapter:
    class: App\ProductsService\Repository\Adapters\Mongo\ProductRepositoryAdapter
